"""Generate docs/llms-full.txt: the README plus the module docs an LLM needs, in one file.

    uv run python scripts/build_llms_full.py           # write docs/llms-full.txt
    uv run python scripts/build_llms_full.py --check   # exit 1 if it is out of date (used in CI)

Module docs are read from the source with `ast`, so nothing is imported and the file can never drift from the code.
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "llms-full.txt"
MODULES = ["log_ui/contract.py", "log_ui/api.py", "log_ui/series.py", "log_ui/views.py", "log_ui/settings.py"]
DOCUMENTED_DEFS = {  # public functions/classes whose docstrings describe behaviour users rely on
    "log_ui/series.py": ["smooth", "downsample_indices", "rolling_bands", "to_payload", "parse_bands"],
    "log_ui/views.py": ["ViewSpec", "PanelSpec", "Category", "MetricOption", "resolve_view", "pick_step"],
}


def module_section(rel: str) -> str:
    tree = ast.parse((ROOT / rel).read_text())
    parts = [f"## {rel}", "", (ast.get_docstring(tree) or "").strip()]
    wanted = DOCUMENTED_DEFS.get(rel, [])
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)) and node.name in wanted:
            doc = ast.get_docstring(node)
            fields = ""
            if isinstance(node, ast.ClassDef):
                names = [
                    s.target.id
                    for s in node.body
                    if isinstance(s, ast.AnnAssign) and isinstance(s.target, ast.Name)
                ]
                fields = f" (fields: {', '.join(names)})" if names else ""
            parts += ["", f"### {node.name}{fields}", "", (doc or "").strip()]
    return "\n".join(parts).rstrip() + "\n"


def build() -> str:
    readme = (ROOT / "README.md").read_text()
    readme = "\n".join(
        line for line in readme.splitlines() if not line.startswith(("[![", "!["))
    )  # badges, images
    header = (
        "# log-ui: full reference\n\n"
        "> Generated by scripts/build_llms_full.py from README.md and module docstrings. "
        "Source: https://github.com/AadityaSalgarkar/log-ui\n\n"
    )
    return (
        header + readme.strip() + "\n\n# Module reference\n\n" + "\n".join(module_section(m) for m in MODULES)
    )


def main() -> None:
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit("docs/llms-full.txt is out of date: run `uv run python scripts/build_llms_full.py`")
        print("docs/llms-full.txt is up to date")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text) // 1024} KB)")


if __name__ == "__main__":
    main()
